services:
  scylla1:
    image: scylladb/scylla:5.4
    container_name: scylla1
    hostname: scylla1
    command:
      - --rpc-address
      - 0.0.0.0
      - --broadcast-rpc-address
      - 127.0.0.1
      - --skip-wait-for-gossip-to-settle
      - "0"
      - --developer-mode
      - "1"
      - --smp
      - "2"
    ports:
      - "10001:10000"
      - "9041:9042"

  scylla2:
    image: scylladb/scylla:5.4
    container_name: scylla2
    hostname: scylla2
    command:
      - --seeds
      - scylla1
      - --rpc-address
      - 0.0.0.0
      - --broadcast-rpc-address
      - 127.0.0.1
      - --skip-wait-for-gossip-to-settle
      - "0"
      - --developer-mode
      - "1"
      - --smp
      - "2"
    ports:
      - "10002:10000"
      - "9042:9042"

  scylla3:
    image: scylladb/scylla:5.4
    container_name: scylla3
    hostname: scylla3
    command:
      - --seeds
      - scylla1
      - --rpc-address
      - 0.0.0.0
      - --broadcast-rpc-address
      - 127.0.0.1
      - --skip-wait-for-gossip-to-settle
      - "0"
      - --developer-mode
      - "1"
      - --smp
      - "2"
    ports:
      - "10003:10000"
      - "9043:9042"

networks:
  default:
    driver: bridge
